---
title: "Was uns am Laufen hält: Vorhersagen von Bewegungsadhärenz durch Affekt und Attributionsstile"
shorttitle: "Affekt, Attribution und Bewegungsadhärenz"
author:
  - name: Enno Winkler
    corresponding: false
    orcid: 0000-0000-0000-0001
    email: janedoe@generic.edu
    affiliations:
      - name: Fernuniversität Hagen
        department: Lehrgebiet Gesundheitspsychologie, Externer Betreuer Dr. Sascha Leisterer (Humboldt-Universität zu Berlin)
        address: 1234 Capital St.
        city: New York
        region: NY
        country: USA
        postal-code: 12084-1234
author-note:
  status-changes: 
    affiliation-change: ~
    deceased: ~
  disclosures:
    study-registration: ~
    data-sharing: ~
    related-report: ~
    conflict-of-interest: ~
    financial-support: ~
    gratitude: ~
    authorship-agreements: ~
abstract: "This document is a template."
keywords: [keyword1, keyword2, keyword3]
bibliography: bibliography.bib
lang: de
format:
  apaquarto-docx: default
 #apaquarto-html: default
 #apaquarto-typst: 
   #keep-typ: true
  #apaquarto-pdf:
    # Can be jou (journal), man (manuscript), stu (student), or doc (document)
    #documentmode: man
    #keep-tex: true
knitr: 
  opts_chunk: 
    message: false
    warning: false
project:
     execute-dir: project
---

# Method

```{r Running scripts}
#| echo: false
#| eval: true 
if (!requireNamespace("xfun", quietly = TRUE)) {
  install.packages("xfun")
}
if (!requireNamespace("knitr", quietly = TRUE)) {
  install.packages("knitr")
}
if (!requireNamespace("rmarkdown", quietly = TRUE)) {
  install.packages("rmarkdown")
}
library(xfun)
source(magic_path("Functions_and_Packages.R"))
source(magic_path("Import+Bereinigung.R"))
source(magic_path("Values.R")); source(magic_path("Graphs.R"))
```

Die Richtlinien hinsichtlich der WHO zu regelmäßiger körperlicher Aktivität [@WHO2010] werden von nur etwa 26% der erwachsenen Bevölkerung in Deutschland in Bezug auf Muskel- und Ausdauertraining erreicht [@RKI_2022]. Die Folgen Physischer Inaktivität...

## Physische Aktivität und Bewegung

Physische Aktivität (physical activity [PA]), auch *körperliche Aktivität* [z.B. @Krug2013] wird in vielen Definitionen als mechanistisch verstanden. So definiert @caspersen1985physical physische Aktivität als jedwede Aktivität der Skelettmuskeln, die einen Energieumsatz zur Folge hat. Andere Autor:innen unterscheiden sich in der Definition von physischer Aktivät in den Bedeutungsnuancen. So spezifizieren beispielsweise @hollmann2009sportmedizin, dass die Aktivität in einer *Steigerung* des Energieumsatzes resultieren muss, um als PA zu gelten. Zweifelsohne sind klare und einfache Definitionen essenziell für den wissenschaftlichen Zugang zu diesem Phänomen. @Piggin2020 argumentiert jedoch, dass diese reduktionistische Auffassung von PA wird dem komplexen Erleben und Verhalten im Zusammenhang mit physicher Aktivität nicht gerecht wird und steht einer ganzheitlichen Betrachtung im Wege steht. Das ist auch im Einklang mit dem Biopsychosozialen Ansatz \[\[\[LIT\]\]\]. Um den Zusammenhang psychischer Phänomene (Affekt, Attribution) mit PA in dem Kontext der Gesundheitsförderung zu diskutieren, übernehme ich daher die Definition von @Piggin2020: "Physical activity involves people moving, acting and performing within culturally specific spaces and contexts, and influenced by a unique array of interests, emotions, ideas, instructions and relationships." (S. 5).

Bewegungsadhärenz (exercise adherence, z.B. [@Mcauley1994]) beinhaltet das Einhalten von selbst-oder fremdgesetzten Zielen im Zusammenhang mit PA [@Buckworth2007] und hat in der Regel das Ziel der Bewegungsförderung in einem gesundheitlichen Kontext [@Ainsworth2020]. 

## Affekt

In dieser Arbeit

-   Definition PA

-   Gesundheitliche Vorteile PA

-   Empfohlene PA

-   Sportmangel Prävalenz

-   Zusammenhang Bewegungsmangel - Krankheiten

-   Messmethoden allgemein –\> Vorteile von Session RPE

## Stichprobe:

Daten von aktiven, erwachsenen Freizeitsportler:innen (Alter ± Standardabweichung: 35.85 ± 12.89 Jahre; 6 weiblich; 12 männlich; 3 divers) liegen bereits aus dem Forschungsprojekt vor.

## Durchführung:

Die Freizeitsportler:innen berichteten vor der Studie ihr generelles Affekterleben innerhalb der letzten zehn Tage mit der Positive and Negative Affect-Scale (PANAS) von @Watson1988. Der Prä-Test enthielt außerdem die Skala von @Peterson1982 zum Attributionsstil und die Items zu demografischen Daten.

Darauf folgte die Trainingsphase, in der die Trainierenden über einen Zeitraum von maximal zwei Monaten sechs Trainingseinheiten dokumentieren sollten. In den Befragungen dazu wurde nach einer Trainingseinheit die wahrgenommene Trainingsintensität mithilfe des Session-RPE-Fragebogens von @Foster2021 erfasst. Nach jeder Trainingseinheit wurde der Affekt mit der PANAS erhoben. Außerdem wurde das Kilometerziel sowie die Dauer des Laufs und die tatsächlich erreichten Kilometer erfasst. Bezüglich des Vorgehens beim Verfassen der Arbeit ist ein Zeitplan am Ende des Dokuments angehängt. [@Amireault2013]

# Methode

Instrumente: Session RPE, Attributionsstil, PANAS

# Ergebnisse

die leute waren `r descriptives_list$Age_mean` alt

::: landscape
`r ave_corr_table`
:::

# Diskussion

# Literaturverzeichnis

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::

# Anhang
